### ISSUE TITLE
npm install failed (ext4)

### ISSUE THREAD

**Issue by Sogl** [vivid-planet/kwf-app-demo#5]
Tried to update by composer ... for nothing:

```
c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing koala-framework/kwf-modernizr (3.8.x-dev)
  - Installing mouf/nodejs-installer (v1.0.4)
    Loading from cache

  - Updating koala-framework/sourcemaps (dev-master e31b2ea => v0.2.0)
    Checking out 4fed293372f516b5cc86ca090f7930e1ea113a7b

  - Removing koala-framework/zendframework1 (v1.12.6-p1)
  - Installing koala-framework/zendframework1 (v1.12.6-p2)
    Loading from cache

  - Updating koala-framework/composer-extra-assets (dev-master 928695b => v1.1.0)
    Checking out 4860eb4c7041824559962a0fc1a3b139fc501444

  - Removing koala-framework/library-swfupload (v2.2.0.1)
  - Installing koala-framework/library-swfupload (v2.2.0.2)
    Loading from cache

  - Installing sepia/po-parser (4.2.0)
    Downloading: 100%

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/finder (v2.6.6)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.6.6)
    Loading from cache

  - Removing symfony/process (v2.6.4)
  - Installing symfony/process (v2.6.6)
    Downloading: 100%

  - Installing koala-framework/file-watcher (dev-master 3a767b7)
    Cloning 3a767b7c46ac8fe45ce0aa94088908bad09171b0

  - Installing symfony/console (v2.6.6)
    Loading from cache

  - Updating koala-framework/koala-framework dev-master (7223589 => d9638eb)
    Checking out d9638eb2ca13789874a9b7525f4970abdc4b2f6a

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Writing lock file
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-deftjs'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...
/
npm ERR! Error: write EPIPE
npm ERR!     at errnoException (net.js:904:11)
npm ERR!     at Object.afterWrite (net.js:720:19)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! syscall write
npm ERR! code EPIPE
npm ERR! errno EPIPE

npm install failed

installing bower dependencies...
bower tinymce#4.1.9             cached git://github.com/tinymce/tinymce.git#4.1.9
bower tinymce#4.1.9           validate 4.1.9 against git://github.com/tinymce/tinymce.git#4.1.9
bower matches-selector#1.0.3       not-cached git://github.com/desandro/matches-selector.git#1.0.3
bower matches-selector#1.0.3          resolve git://github.com/desandro/matches-selector.git#1.0.3
bower matches-selector#1.0.3         download https://github.com/desandro/matches-selector/archive/v1.0.3.tar.gz
bower matches-selector#1.0.3          extract archive.tar.gz
bower matches-selector#1.0.3         resolved git://github.com/desandro/matches-selector.git#1.0.3
bower tinymce#4.1.9                   install tinymce#4.1.9
bower matches-selector#1.0.3          install matches-selector#1.0.3

tinymce#4.1.9 vendor\bower_components\tinymce

matches-selector#1.0.3 vendor\bower_components\matches-selector

c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-deftjs'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...

installing bower dependencies...

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php clear-cache
[ 1/8] clearing component... OK (0ms)
[ 2/8] clearing model....... OK (9ms)
[ 3/8] clearing simple...... OK (112ms)
[ 4/8] clearing config...... OK (1ms)
[ 5/8] clearing setup....... OK (0ms)
[ 6/8] clearing assets...... OK (36ms)
[7/8] refreshing config.... OK (37ms)
[8/8] refreshing setup..... OK (276ms)

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php build
[ 1/3] building trl...... exception 'Exception' with message 'PoParser: Parse error! Unknown key "<html><body></body></html>" on line <html><body></body></html>' in C:\OpenServer\domains\kwfapp-ext4\vendor\sepia\po-parser\src\Sepia\PoParser.php:310
Stack trace:
#0 C:\OpenServer\domains\kwfapp-ext4\vendor\sepia\po-parser\src\Sepia\PoParser.php(97): Sepia\PoParser->parse(Object(Sepia\FileHandler))
#1 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Trl.php(113): Sepia\PoParser->parseFile('vendor/koala-fr...')
#2 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Trl.php(77): Kwf_Util_Build_Types_Trl->_getPoParsers('kwf', 'ru')
#3 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Trl.php(66): Kwf_Util_Build_Types_Trl->_loadTrlArray('kwf', 'ru', true)
#4 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Trl->_build(Array)
#5 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#6 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#7 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#8 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#9 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#10 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#11 C:\OpenServer\domains\kwfapp-ext4\bootstrap.php(31): Kwf_Controller_Front->dispatch()
#12 {main} [ERROR] (2765ms)
[ 2/3] building events... OK (101ms)
[ 3/3] building assets...
calculating dependencies...
 42% [#########------------] Admin js                                          exception 'Kwf_Exception' with message 'build/trl/kwfru was not created in build' in C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php:405
Stack trace:
#0 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php(428): Kwf_Trl->_loadTrlElements('kwf', 'ru', false)
#1 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php(335): Kwf_Trl->_findElement('Useradministrat...', 'kwf', '', NULL)
#2 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php(315): Kwf_Trl->_trlc('', 'Useradministrat...', Array, 'kwf', NULL)
#3 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php(71): Kwf_Trl->trlKwf('Useradministrat...', Array)
#4 C:\OpenServer\domains\kwfapp-ext4\app\Acl.php(55): trlKwf('Useradministrat...')
#5 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Acl.php(23): Acl->__construct()
#6 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets\AclControllerProvider.php(8): Kwf_Acl::getInstance()
#7 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Ext_Assets_AclControllerProvider->getDependency('Ext4AclControll...')
#8 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(35): Kwf_Assets_ProviderList_Abstract->findDependency('Ext4AclControll...')
#9 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('AdminIniDep')
#10 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\IniNoFiles.php(10): Kwf_Assets_ProviderList_Abstract->findDependency('AdminIniDep')
#11 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_IniNoFiles->getDependency('Admin')
#12 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(28): Kwf_Assets_ProviderList_Abstract->findDependency('Admin')
#13 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(81): Kwf_Assets_Package->getDependency()
#14 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(75): Kwf_Assets_Package->_getFilteredUniqueDependencies('text/javascript')
#15 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(140): Kwf_Assets_Package->getFilteredUniqueDependencies('text/javascript')
#16 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#17 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#18 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#19 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#20 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#21 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#22 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#23 C:\OpenServer\domains\kwfapp-ext4\bootstrap.php(31): Kwf_Controller_Front->dispatch()
#24 {main} [ERROR] (4692ms)

c:\OpenServer\domains\kwfapp-ext4>
```

**Comment by nsams** [comment]
Known bug in Kwf, I created an issue: https://github.com/koala-framework/koala-framework/issues/331

**Comment by Sogl** [comment]
But the npm error message looks like nodejs-installer bug...

**Comment by nsams** [comment]
yes, but on the second run the error is gone.

can you reproduce the problem?

**Comment by Sogl** [comment]
> can you reproduce the problem?

Yes:

```
c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing mouf/nodejs-installer (v1.0.4)
  - Installing mouf/nodejs-installer (v1.0.5)
    Downloading: 100%

Writing lock file
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-deftjs'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...

installing bower dependencies...

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php clear-cache
[ 1/8] clearing component... OK (0ms)
[ 2/8] clearing model....... OK (18ms)
[ 3/8] clearing simple...... OK (212ms)
[ 4/8] clearing config...... OK (1ms)
[ 5/8] clearing setup....... OK (0ms)
[ 6/8] clearing assets...... OK (97ms)
[7/8] refreshing config.... OK (136ms)
[8/8] refreshing setup..... OK (541ms)

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php build
[ 1/3] building trl...... exception 'Exception' with message 'PoParser: Parse error! Unknown key "<html><body></body></html>" on line <html><body></body></html>' in C:\OpenServer\domains\kwfapp-ext4\vendor\sepia\po-parser\src\Sepia\PoParser.php:310
Stack trace:
#0 C:\OpenServer\domains\kwfapp-ext4\vendor\sepia\po-parser\src\Sepia\PoParser.php(97): Sepia\PoParser->parse(Object(Sepia\FileHandler))
#1 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Trl.php(113): Sepia\PoParser->parseFile('vendor/koala-fr...')
#2 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Trl.php(77): Kwf_Util_Build_Types_Trl->_getPoParsers('kwf', 'ru')
#3 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Trl.php(66): Kwf_Util_Build_Types_Trl->_loadTrlArray('kwf', 'ru', true)
#4 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Trl->_build(Array)
#5 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#6 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#7 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#8 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#9 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#10 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#11 C:\OpenServer\domains\kwfapp-ext4\bootstrap.php(31): Kwf_Controller_Front->dispatch()
#12 {main} [ERROR] (331ms)
[ 2/3] building events... OK (437ms)
[ 3/3] building assets...
calculating dependencies...
 42% [#########------------] Admin js                                          exception 'Kwf_Exception' with message 'build/trl/kwfru was not created in build' in C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php:405
Stack trace:
#0 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php(428): Kwf_Trl->_loadTrlElements('kwf', 'ru', false)
#1 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php(335): Kwf_Trl->_findElement('Useradministrat...', 'kwf', '', NULL)
#2 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php(315): Kwf_Trl->_trlc('', 'Useradministrat...', Array, 'kwf', NULL)
#3 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Trl.php(71): Kwf_Trl->trlKwf('Useradministrat...', Array)
#4 C:\OpenServer\domains\kwfapp-ext4\app\Acl.php(55): trlKwf('Useradministrat...')
#5 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Acl.php(23): Acl->__construct()
#6 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets\AclControllerProvider.php(8): Kwf_Acl::getInstance()
#7 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Ext_Assets_AclControllerProvider->getDependency('Ext4AclControll...')
#8 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(35): Kwf_Assets_ProviderList_Abstract->findDependency('Ext4AclControll...')
#9 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('AdminIniDep')
#10 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\IniNoFiles.php(10): Kwf_Assets_ProviderList_Abstract->findDependency('AdminIniDep')
#11 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_IniNoFiles->getDependency('Admin')
#12 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(28): Kwf_Assets_ProviderList_Abstract->findDependency('Admin')
#13 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(81): Kwf_Assets_Package->getDependency()
#14 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(75): Kwf_Assets_Package->_getFilteredUniqueDependencies('text/javascript')
#15 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(140): Kwf_Assets_Package->getFilteredUniqueDependencies('text/javascript')
#16 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#17 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#18 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#19 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#20 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#21 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#22 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#23 C:\OpenServer\domains\kwfapp-ext4\bootstrap.php(31): Kwf_Controller_Front->dispatch()
#24 {main} [ERROR] (5814ms)

c:\OpenServer\domains\kwfapp-ext4>
```

**Comment by nsams** [comment]
Ok, that problem is https://github.com/koala-framework/koala-framework/issues/331

**Comment by Sogl** [comment]
New:

```
c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing symfony/console (v2.6.6)
  - Installing symfony/console (v2.6.7)
    Loading from cache

  - Removing symfony/process (v2.6.6)
  - Installing symfony/process (v2.6.7)
    Loading from cache

  - Removing symfony/event-dispatcher (v2.6.6)
  - Installing symfony/event-dispatcher (v2.6.7)
    Loading from cache

  - Removing symfony/finder (v2.6.6)
  - Installing symfony/finder (v2.6.7)
    Loading from cache

  - Updating koala-framework/kwf-extjs 1.1.x-dev (998f001 => 7a06073)
    Checking out 7a060734d1ba2b29fbedae56afe8e87f8ded5ce1

  - Removing koala-framework/koala-framework (3.9.x-dev e4500c0)
  - Installing koala-framework/koala-framework (3.9.x-dev 20d2dce)
    Cloning 20d2dce22148e26490af936403fda8991f174ea4
    Failed to download koala-framework/koala-framework from source: The process "git clone --no-checkout "git://github.com/koala-framework/koala-framework.git" "C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework" && cd /D "C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework" && git remote add composer "git://github.com/koala-framework/koala-framework.git" && git fetch composer" exceeded the timeout of 300 seconds.
    Now trying to download from dist
  - Installing koala-framework/koala-framework (3.9.x-dev 20d2dce)
    Downloading: 100%

  - Updating koala-framework/kwf-densajs 1.0.x-dev (0aa4755 => 3d876c0)
    Checking out 3d876c01c47e4b66a16cedcd008bfe8afc8d00c9

Writing lock file
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-deftjs'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...
|




  [RuntimeException]
  npm install failed



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]



c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-deftjs'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...

installing bower dependencies...
bower densajs#591bfbfb37d8bc12c63df69e001bae3b89106f01       not-cached git://github.com/koala-framework/densajs.git#591bfbfb37d8bc12c63df69e001bae3b89106f01
bower densajs#591bfbfb37d8bc12c63df69e001bae3b89106f01          resolve git://github.com/koala-framework/densajs.git#591bfbfb37d8bc12c63df69e001bae3b89106f01
bower densajs#591bfbfb37d8bc12c63df69e001bae3b89106f01         checkout 591bfbfb37d8bc12c63df69e001bae3b89106f01
bower densajs#591bfbfb37d8bc12c63df69e001bae3b89106f01         resolved git://github.com/koala-framework/densajs.git#591bfbfb37
bower densajs#591bfbfb37d8bc12c63df69e001bae3b89106f01          install densajs#591bfbfb37

densajs#591bfbfb37 vendor\bower_components\densajs
тФЬтФАтФА deftjs#0.9.1
тФЬтФАтФА excel-builder#ef049b7c50
тФФтФАтФА extjs#4.2.1-883

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php clear-cache

wrote offline bootstrap.php

[ 1/8] clearing component... OK (1ms)
[ 2/8] clearing model....... OK (9ms)
[ 3/8] clearing simple...... OK (31ms)
[ 4/8] clearing config...... OK (1ms)
[ 5/8] clearing setup....... OK (1ms)
[ 6/8] clearing assets...... OK (15ms)
[7/8] refreshing config.... OK (10ms)
[8/8] refreshing setup..... OK (72ms)

restored bootstrap.php

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php build
[ 1/3] building trl...... OK (0ms)
[ 2/3] building events... OK (32ms)
[ 3/3] building assets...
calculating dependencies...
100% [#####################] Maintenance printcss
compiling assets...
 71% [###############------] kwf/views/user/master.scss                        exception 'Kwf_Exception' with message 'compiling sass failed: C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass
          ^
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\index.js:188:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\render.js:3:12)
    at Module._compile (module.js:460:26)' in C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Dependency\File\Scss.php:92
Stack trace:
#0 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(168): Kwf_Assets_Dependency_File_Scss->warmupCaches()
#1 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#2 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#3 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#4 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#5 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#6 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#7 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\kwfapp-ext4\bootstrap.php(31): Kwf_Controller_Front->dispatch()
#9 {main} [ERROR] (16106ms)

c:\OpenServer\domains\kwfapp-ext4>
```

**Comment by nsams** [comment]
When you get this `libsass bindings not found` error that means the `node-sass` `installation in vendor/koala-framework/koala-framework/node_modules/node-sass` isn't working properly.

Test this by calling `./vendor/bin/node ./vendor/koala-framework/koala-framework/node_modules/node-sass/bin/node-sass`.

Fixing the issue is usually done by re-installing node-sass: simply delete the whole vendor, or just ./vendor/koala-framework/koala-framework/node_modules and composer install will re-install everything.
