### ISSUE TITLE
Kwf_Exception with message 'coffee failed' (ext 4)

### ISSUE THREAD

**Issue by Sogl** [vivid-planet/kwf-app-demo#7]
Hi!

Tried to update kwf and got an error:

```
c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing koala-framework/zendframework1 (v1.12.13)
    Downloading: 100%

  - Installing sepia/po-parser (4.2.0)
    Downloading: 100%

  - Installing symfony/process (v2.6.8)
    Downloading: 100%

  - Installing symfony/console (v2.6.8)
    Downloading: 100%

  - Installing psr/log (1.0.0)
    Downloading: 100%

  - Installing symfony/finder (v2.6.8)
    Downloading: 100%

  - Installing symfony/event-dispatcher (v2.6.8)
    Downloading: 100%

  - Installing koala-framework/file-watcher (dev-master 3a767b7)
    Cloning 3a767b7c46ac8fe45ce0aa94088908bad09171b0

  - Installing koala-framework/sourcemaps (v0.2.0)
    Downloading: 100%

  - Installing twig/twig (v1.16.1)
    Downloading: 100%

  - Installing koala-framework/composer-extra-assets (v1.1.0)
    Downloading: 100%

  - Installing koala-framework/library-css3pie (v1.0.0)
    Downloading: 100%

  - Installing koala-framework/library-htmlawed (v1.1.14)
    Downloading: 100%

  - Installing koala-framework/library-silkicons (v1.3)
    Downloading: 100%

  - Installing koala-framework/library-swfobject (v2.2)
    Downloading: 100%

  - Installing koala-framework/library-swfupload (v2.2.0.2)
    Downloading: 100%

  - Installing koala-framework/extjs2 (v2.3.0-p6)
    Downloading: 100%

  - Installing koala-framework/koala-framework (3.9.x-dev 85c7e38)
    Cloning 85c7e385c8d3197729139998f4b086be49cf1b57

  - Installing koala-framework/kwf-extjs (1.1.x-dev 7a06073)
    Cloning 7a060734d1ba2b29fbedae56afe8e87f8ded5ce1

  - Installing koala-framework/kwf-deftjs (1.0.x-dev a323df1)
    Cloning a323df116c970b211989f2d3be689e49ced65e7c

  - Installing koala-framework/kwf-densajs (1.0.x-dev ca2db8a)
    Cloning ca2db8a8107685d108813ca2b1e4701159c0bf52

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
koala-framework/koala-framework suggests installing phpoffice/phpexcel (Allows exporting as XLS in AutoGrid)
koala-framework/koala-framework suggests installing tecnick.com/tcpdf (Allows generating pdfs from components)
koala-framework/koala-framework suggests installing amazonwebservices/aws-sdk-for-php (Integration with Amazon Web Services)
koala-framework/koala-framework suggests installing reprovinci/solr-php-client (Integration with Solr)
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...
-




  [RuntimeException]
  npm install failed



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]



c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-deftjs'...
coffee-script@1.7.1 node_modules\coffee-script
тФФтФАтФА mkdirp@0.3.5

installing bower dependencies...
bower deftjs#0.9.1              cached git://github.com/deftjs/DeftJS.git#0.9.1 bower deftjs#0.9.1            validate 0.9.1 against git://github.com/deftjs/DeftJS.git#0.9.1
bower tinymce#4.1.9             cached git://github.com/tinymce/tinymce.git#4.1.9
bower tinymce#4.1.9           validate 4.1.9 against git://github.com/tinymce/tinymce.git#4.1.9
bower compass-mixins#1.0.2      cached git://github.com/Igosuki/compass-mixins.git#1.0.2
bower compass-mixins#1.0.2    validate 1.0.2 against git://github.com/Igosuki/compass-mixins.git#1.0.2
bower jquery#1.11.1             cached git://github.com/jquery/jquery.git#1.11.1

bower jquery#1.11.1           validate 1.11.1 against git://github.com/jquery/jquery.git#1.11.1
bower underscore#1.7.0          cached git://github.com/jashkenas/underscore.git#1.7.0
bower underscore#1.7.0        validate 1.7.0 against git://github.com/jashkenas/underscore.git#1.7.0
bower jquery.transit#0.9.9      cached git://github.com/rstacruz/jquery.transit.git#0.9.9
bower jquery.transit#0.9.9    validate 0.9.9 against git://github.com/rstacruz/jquery.transit.git#0.9.9
bower jquery.easing#1.3.0       cached git://github.com/jozefizso/bower-jquery-easing.git#1.3.0
bower jquery.easing#1.3.0     validate 1.3.0 against git://github.com/jozefizso/bower-jquery-easing.git#1.3.0
bower susy#8161395e8ad5d75a0a15a0355feb9853ebaad369           cached git://github.com/vivid-planet/susy.git#8161395e8a
bower susy#8161395e8ad5d75a0a15a0355feb9853ebaad369         validate 8161395e8a against git://github.com/vivid-planet/susy.git#8161395e8ad5d75a0a15a0355feb9853ebaad369
bower densajs#6059d1b0a29aece4fd697a891e823a2061c82e08        cached git://github.com/koala-framework/densajs.git#6059d1b0a2
bower densajs#6059d1b0a29aece4fd697a891e823a2061c82e08      validate 6059d1b0a2 against git://github.com/koala-framework/densajs.git#6059d1b0a29aece4fd697a891e823a2061c82e08
bower excel-builder#ef049b7c500caf598a15fe2a9243a83a8c14927b  cached git://github.com/stephenliberty/excel-builder.js.git#ef049b7c50
bower excel-builder#ef049b7c500caf598a15fe2a9243a83a8c14927b         validate ef049b7c50 against git://github.com/stephenliberty/excel-builder.js.git#ef049b7c500caf598a15fe2a9243a83a8c14927b
bower moxie#1.2.1                                                      cached git://github.com/moxiecode/moxie.git#1.2.1
bower moxie#1.2.1                                                    validate 1.2.1 against git://github.com/moxiecode/moxie.git#1.2.1
bower extjs#4.2.1-883                                                  cached git://github.com/koala-framework/extjs.git#4.2.1-883
bower extjs#4.2.1-883                                                validate 4.2.1-883 against git://github.com/koala-framework/extjs.git#4.2.1-883
bower matches-selector#1.0.3                                           cached git://github.com/desandro/matches-selector.git#1.0.3
bower matches-selector#1.0.3                                         validate 1.0.3 against git://github.com/desandro/matches-selector.git#1.0.3
bower moxie#1.2.1                                                         new version for git://github.com/moxiecode/moxie.git#1.2.1
bower moxie#1.2.1                                                     resolve git://github.com/moxiecode/moxie.git#1.2.1
bower moxie#1.2.1                                                    download https://github.com/moxiecode/moxie/archive/1.2.1.tar.gz
bower moxie#1.2.1                                                     extract archive.tar.gz
bower moxie#1.2.1                                                    mismatch Version declared in the json (1.2.0) is different than the resolved one (1.2.1)
bower moxie#1.2.1                                                    resolved git://github.com/moxiecode/moxie.git#1.2.1
bower susy#8161395e8ad5d75a0a15a0355feb9853ebaad369                   install susy#8161395e8a
bower densajs#6059d1b0a29aece4fd697a891e823a2061c82e08                install densajs#6059d1b0a2
bower excel-builder#ef049b7c500caf598a15fe2a9243a83a8c14927b          install excel-builder#ef049b7c50
bower deftjs#0.9.1                                                    install deftjs#0.9.1
bower compass-mixins#1.0.2                                            install compass-mixins#1.0.2
bower tinymce#4.1.9                                                   install tinymce#4.1.9
bower jquery.transit#0.9.9                                            install jquery.transit#0.9.9
bower jquery.easing#1.3.0                                             install jquery.easing#1.3.0
bower underscore#1.7.0                                                install underscore#1.7.0
bower jquery#1.11.1                                                   install jquery#1.11.1
bower extjs#4.2.1-883                                                 install extjs#4.2.1-883
bower matches-selector#1.0.3                                          install matches-selector#1.0.3
bower moxie#1.2.1                                                     install moxie#1.2.1

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php clear-cache

wrote offline bootstrap.php

[ 1/8] clearing component... OK (0ms)
[ 2/8] clearing model....... OK (14ms)
[ 3/8] clearing simple...... OK (96ms)
[ 4/8] clearing config...... OK (2ms)
[ 5/8] clearing setup....... OK (0ms)
[ 6/8] clearing assets...... OK (39ms)
[7/8] refreshing config.... OK (42ms)
[8/8] refreshing setup..... OK (62ms)

restored bootstrap.php

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php build
[ 1/3] building trl...... OK (1ms)
[ 2/3] building events... OK (231ms)
[ 3/3] building assets...
calculating dependencies...
100% [#####################] Maintenance printcss
compiling assets...
 28% [######---------------] deft/core/Class.coffee                            exception 'Kwf_Exception' with message 'coffee failed: "." не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.' in C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\kwf-deftjs\Kwf\DeftJS\Assets\JsDependency.php:36
Stack trace:
#0 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Dependency\File\Js.php(41): Kwf_DeftJS_Assets_JsDependency->_getRawContents(NULL)
#1 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(166): Kwf_Assets_Dependency_File_Js->warmupCaches() #2 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#3 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#4 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#5 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#6 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#7 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#9 C:\OpenServer\domains\kwfapp-ext4\bootstrap.php(31): Kwf_Controller_Front->dispatch()
#10 {main} [ERROR] (13459ms)

c:\OpenServer\domains\kwfapp-ext4>
```

**Comment by nsams** [comment]
I added debug output in https://github.com/koala-framework/kwf-deftjs/commit/dc57a846bf1974e0073aeb261a733af5772210f6

please composer update and post the output you get.

**Comment by Sogl** [comment]
Output:

```
c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating koala-framework/kwf-extjs 1.1.x-dev (7a06073 => 150b3f2)
    Checking out 150b3f2e69b9c4d88f26a73c9f98a10bcd039632

  - Updating koala-framework/kwf-deftjs 1.0.x-dev (a323df1 => dc57a84)
    Checking out dc57a846bf1974e0073aeb261a733af5772210f6

  - Updating koala-framework/kwf-densajs 1.0.x-dev (ca2db8a => 98d5136)
    Checking out 98d513656bef679952c68835a03c7eaba42178c8

Writing lock file
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-deftjs'...

installing bower dependencies...
bower densajs#680f8004863d0cad596dfd448c12bd6a5da253ed       not-cached git://github.com/koala-framework/densajs.git#680f8004863d0cad596dfd448c12bd6a5da253ed
bower densajs#680f8004863d0cad596dfd448c12bd6a5da253ed          resolve git://github.com/koala-framework/densajs.git#680f8004863d0cad596dfd448c12bd6a5da253ed
bower densajs#680f8004863d0cad596dfd448c12bd6a5da253ed         checkout 680f8004863d0cad596dfd448c12bd6a5da253ed
bower densajs#680f8004863d0cad596dfd448c12bd6a5da253ed         resolved git://github.com/koala-framework/densajs.git#680f800486
bower densajs#680f8004863d0cad596dfd448c12bd6a5da253ed          install densajs#680f800486

densajs#680f800486 vendor\bower_components\densajs
тФЬтФАтФА deftjs#0.9.1
тФЬтФАтФА excel-builder#ef049b7c50
тФФтФАтФА extjs#4.2.1-883

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php clear-cache

wrote offline bootstrap.php

[ 1/8] clearing component... OK (1ms)
[ 2/8] clearing model....... OK (12ms)
[ 3/8] clearing simple...... OK (213ms)
[ 4/8] clearing config...... OK (1ms)
[ 5/8] clearing setup....... OK (0ms)
[ 6/8] clearing assets...... OK (60ms)
[7/8] refreshing config.... OK (64ms)
[8/8] refreshing setup..... OK (55ms)

restored bootstrap.php

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php build
[ 1/3] building trl...... OK (13ms)
[ 2/3] building events... OK (421ms)
[ 3/3] building assets...
calculating dependencies...
100% [#####################] Maintenance printcss
compiling assets...
 28% [######---------------] deft/core/Class.coffee                            exception 'Kwf_Exception' with message 'coffee failed: ./vendor/bin/node C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\kwf-deftjs/node_modules/coffee-script/bin/coffee -cb C:\OpenServer\domains\kwfapp-ext4\temp\cof2FD1.tmp  2>&1
"." not an internal or external
command, operable program or batch file.' in C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\kwf-deftjs\Kwf\DeftJS\Assets\JsDependency.php:36
Stack trace:
#0 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Dependency\File\Js.php(41): Kwf_DeftJS_Assets_JsDependency->_getRawContents(NULL)
#1 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(166): Kwf_Assets_Dependency_File_Js->warmupCaches() #2 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#3 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#4 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#5 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#6 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#7 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#9 C:\OpenServer\domains\kwfapp-ext4\bootstrap.php(31): Kwf_Controller_Front->dispatch()
#10 {main} [ERROR] (116437ms)

c:\OpenServer\domains\kwfapp-ext4>
```

**Comment by nsams** [comment]
should be fixed with https://github.com/koala-framework/kwf-deftjs/commit/def71f3be1ff4e8d2933e48afa5dc7a3eeee230c

**Comment by Sogl** [comment]
Node-sass.. again...
https://github.com/koala-framework/koala-framework/issues/349

Output:

```
c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating koala-framework/kwf-deftjs 1.0.x-dev (dc57a84 => def71f3)
    Checking out def71f3be1ff4e8d2933e48afa5dc7a3eeee230c

  - Updating koala-framework/kwf-densajs 1.0.x-dev (98d5136 => f2e449a)
    Checking out f2e449aad4276aa1bd0be18f3930484de4407768

Writing lock file
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-deftjs'...

installing bower dependencies...
bower densajs#63e5fb264fb13bf6d3fbe435e2d4994db1714998       not-cached git://github.com/koala-framework/densajs.git#63e5fb264fb13bf6d3fbe435e2d4994db1714998
bower densajs#63e5fb264fb13bf6d3fbe435e2d4994db1714998          resolve git://github.com/koala-framework/densajs.git#63e5fb264fb13bf6d3fbe435e2d4994db1714998
bower densajs#63e5fb264fb13bf6d3fbe435e2d4994db1714998         checkout 63e5fb264fb13bf6d3fbe435e2d4994db1714998
bower densajs#63e5fb264fb13bf6d3fbe435e2d4994db1714998         resolved git://github.com/koala-framework/densajs.git#63e5fb264f
bower densajs#63e5fb264fb13bf6d3fbe435e2d4994db1714998          install densajs#63e5fb264f

densajs#63e5fb264f vendor\bower_components\densajs
тФЬтФАтФА deftjs#0.9.1
тФЬтФАтФА excel-builder#ef049b7c50
тФФтФАтФА extjs#4.2.1-883

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php clear-cache

wrote offline bootstrap.php

[ 1/8] clearing component... OK (0ms)
[ 2/8] clearing model....... OK (15ms)
[ 3/8] clearing simple...... OK (179ms)
[ 4/8] clearing config...... OK (1ms)
[ 5/8] clearing setup....... OK (1ms)
[ 6/8] clearing assets...... OK (73ms)
[7/8] refreshing config.... OK (81ms)
[8/8] refreshing setup..... OK (57ms)

restored bootstrap.php

c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php build
[ 1/3] building trl...... OK (13ms)
[ 2/3] building events... OK (404ms)
[ 3/3] building assets...
calculating dependencies...
100% [#####################] Maintenance printcss
compiling assets...
 67% [##############-------] kwfext/Kwf_js/Ext4/form/field/File.scss           exception 'Kwf_Exception' with message 'compiling sass failed: C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass
          ^
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\index.js:188:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\node_modules\node-sass\lib\render.js:3:12)
    at Module._compile (module.js:460:26)' in C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Dependency\File\Scss.php:92
Stack trace:
#0 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(166): Kwf_Assets_Dependency_File_Scss->warmupCaches()
#1 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#2 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#3 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#4 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#5 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#6 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#7 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\kwfapp-ext4\bootstrap.php(31): Kwf_Controller_Front->dispatch()
#9 {main} [ERROR] (117123ms)

c:\OpenServer\domains\kwfapp-ext4>
```

**Comment by nsams** [comment]
Ok, that means the coffee issue is fixed!

the node-sass issue we handle here: https://github.com/koala-framework/koala-framework/issues/349
